trigger:
  branches:
    include:
    - main
  paths:
   include:
     - 'azure-pipelines.yml'
     - 'tasks/**/*'

jobs:
  - job: Secrets_Check
    pool:
      vmImage: 'windows-latest'
    steps:
    # Get JWT from Azure Service Principal so we can use it for the akeyless-auth@0 task
    - task: AzureCLI@2
      name: 'AzureCLI'
      displayName: 'Get JWT from Azure Service Principal'
      inputs:
        azureSubscription: 'Azure MSA Account'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $JWT=$(az account get-access-token --query accessToken --output tsv)
          echo "##vso[task.setvariable variable=azure_jwt;isoutput=true;issecret=true]$JWT"

# Important: The 'connectedServiceName` is a service you've added in your AzDO project settings. It simply holds your Akeyless Access ID (ex. 'p-xxxxxxx').
# Once you have a valid Akeyless token, you can use it to retrieve static and dynamic secrets later
    - task: akeyless-auth@0
      name: AkeylessAuth
      displayName: 'Get Akeyless Access Token'
      inputs:
        connectedServiceName: 'PersonalAkeylessVault'
        jwt: '$(AzureCLI.azure_jwt)'

# Static secrets retrieval

    - task: akeyless-get-secrets-value-task@0
      displayName: 'Get Static Secrets'
      inputs:
        connectedServiceName: 'PersonalAkeylessVault'
        token: '$(AkeylessAuth.akeylessToken)'
        secretsPaths: 'nuget_key=/progress/TELERIK_NUGET_KEY,my_cool_secret=/samples/azdo-test-secret'

    - powershell: |
        echo "---------------------------------------------"
        echo "Static secrets can simply be referenced by the"
        echo "output variable name you set in the task input."
        echo "---------------------------------------------"
        
        echo "Verifying static secrets..."
        echo "nuget_key: $(nuget_key)"
        echo "my_cool_secret: $(my_cool_secret)"
      displayName: 'Checking static Secrets'

# Dynamic secrets retrieval

    - task: akeyless-get-dynamic-secret-value-task@0
      name: AkeylessSqlDynamic
      displayName: 'Get SQL Dynamic Secret'
      inputs:
        connectedServiceName: 'PersonalAkeylessVault'
        token: '$(AkeylessAuth.akeylessToken)'
        name: '/az-dvlup-sqlsrvsecret'
        timeout: 30

    - powershell: |
        echo "---------------------------------------------------------------------------------------------"
        echo "Dynamic secrets need to be parsed from the 'dynamicSecretValue' output variable of the task."
        echo "---------------------------------------------------------------------------------------------"
        echo "Verifying SQL dynamic secret..."

        $username=$(echo "$(AkeylessSqlDynamic.dynamicSecretValue)" | jq -r '.user')
        $password=$(echo "$(AkeylessSqlDynamic.dynamicSecretValue)" | jq -r '.password')
        $ttl=$(echo "$(AkeylessSqlDynamic.dynamicSecretValue)" | jq -r '.ttl_in_minutes')
        $id=$(echo "$(AkeylessSqlDynamic.dynamicSecretValue)" | jq -r '.id')
        echo "SQL CONFIRMATION - User: $username, Password: $password, TTL: $ttl, Id: $id"
      displayName: 'Checking Secrets'

    - task: akeyless-get-dynamic-secret-value-task@0
      name: AkeylessEntraDynamic
      displayName: 'Get Entra ID Dynamic Secret'
      inputs:
        connectedServiceName: 'PersonalAkeylessVault'
        token: '$(AkeylessAuth.akeylessToken)'
        name: '/az-dvlup-sqlsrvsecret'
        timeout: 30

    - powershell: |
        echo "---------------------------------------------------------------------------------------------"
        echo "Dynamic secrets need to be parsed from the 'dynamicSecretValue' output variable of the task."
        echo "---------------------------------------------------------------------------------------------"
        echo "Verifying Entra Id dynamic secret..."

        keyId=$(echo "$(AkeylessEntraDynamic.dynamicSecretValue)" | jq -r '.keyId')
        displayName=$(echo "$(AkeylessEntraDynamic.dynamicSecretValue)" | jq -r '.displayName')
        appId=$(echo "$(AkeylessEntraDynamic.dynamicSecretValue)" | jq -r '.appId')
        tenantId=$(echo "$(AkeylessEntraDynamic.dynamicSecretValue)" | jq -r '.tenantId')
        secretText=$(echo "$(AkeylessEntraDynamic.dynamicSecretValue)" | jq -r '.secretText')
        echo "keyId: $keyId, displayName: $displayName, appId: $appId, tenantId: $tenantId, secretText: $secretText"
      displayName: 'Checking Secrets'


# Original
    # Test static secrets retrieval
    # - task: akeyless-secrets@1
    #   name: 'AkeylessStatic'
    #   displayName: 'Get Static Secrets'
    #   inputs:
    #     accessid: 'p-sxfgaph9urt4om'
    #     azureJwt: '$(AzureCLI.azure_jwt)'
    #     staticSecrets: '{"/progress/TELERIK_NUGET_KEY":"NUGET_KEY"}'

    # Test dynamic secrets retrieval
    # - task: akeyless-secrets@1
    #   name: 'AkeylessSqlDynamic'
    #   displayName: 'Get SQL Dynamic Secret'
    #   inputs:
    #     accessid: 'p-sxfgaph9urt4om'
    #     azureJwt: '$(AzureCLI.azure_jwt)'
    #     dynamicSecrets: '{"/az-dvlup-sqlsrvsecret":"sql_dynamic_secret"}'

    # - powershell: |
    #     # SQL example
    #     # "{\"user\":\"tmp_az-dvlup-sqlsr_lancedvlup_com_123AB\",\"password\":\"ABC~3eF=12345r3\",\"ttl_in_minutes\":\"60\",\"id\":\"tmp_az-dvlup-sqlsr_lancedvlup_com_123AB\"}"

    #     Write-Host "User: $(AkeylessSqlDynamic.sql_dynamic_secret)"

    #     $jsonObject = "$(AkeylessSqlDynamic.sql_dynamic_secret)" | ConvertFrom-Json
    #     $user = $jsonObject.user
    #     $password = $jsonObject.password
    #     $ttl = $jsonObject.ttl_in_minute
    #     $id = $jsonObject.id
        
    #     Write-Host "User: $user"
    #     Write-Host "Password: $password"
    #     Write-Host "TTL: $ttl
    #     Write-Host "Id: $id"
    #   displayName: 'Check SQL Dynamic Secret output'

    # - task: akeyless-secrets@1
    #   name: 'AkeylessEntraDynamic'
    #   displayName: 'Get Entra Dynamic Secret'
    #   inputs:
    #     accessid: 'p-sxfgaph9urt4om'
    #     azureJwt: '$(AzureCLI.azure_jwt)'
    #     dynamicSecrets: '{"/entra-id-live":"entra_dynamic_secret"}'

    # - powershell: |
    #     # Entra ID Response Example
    #     # "{\"secret\":{\"keyId\":\"eff4031b-8b5c-4da6-b76f-05e70790d326\",\"displayName\":\"tmp.lancedvlupcom.LzlSh\",\"secretText\":\"ABCDEFG~BW1WQNBfaQoSeWmjfSxqm123456awM\",\"appId\":\"207ff3fc-f6e3-442e-babf-55b62e047be7\",\"tenantId\":\"bd47e796-3473-4b8a-9101-1f4c0c7af31a\",\"endDateTime\":\"2025-10-01T22:44:08.5970399Z\"},\"ttl_in_minutes\":\"60\",\"id\":\"{\\\"secret_name\\\":\\\"tmp.lancedvlupcom.LzlSh\\\",\\\"secret_key_id\\\":\\\"eff4031b-8b5c-4da6-b76f-05e70790d326\\\"}\",\"msg\":\"User  has been added successfully to the following\\nGroup(s): []\\nRole(s): []\\nExpires on Tue Sep 30 23:44:09 UTC 2025\"}"

    #     Write-Host "User: $(AkeylessEntraDynamic.entra_dynamic_secret)"

    #     $jsonObject = "$(AkeylessEntraDynamic.entra_dynamic_secret)" | ConvertFrom-Json
    #     $keyId = $jsonObject.secret.keyId
    #     $displayName = $jsonObject.secret.displayName
    #     $appId = $jsonObject.secret.appId
    #     $tenantId = $jsonObject.secret.tenantId
    #     $secretText = $jsonObject.secret.secretText
    #     $endDateTime = $jsonObject.secret.endDateTime
    #     Write-Output "keyId: $keyId, displayName: $displayName, appId: $appId, tenantId: $tenantId, secretText: $secretText, TTL (minutes): $ttl, endDateTime: $endDateTime"
    #   displayName: 'Check EntraID Dynamic Secret output'