trigger:
  branches:
    include:
    - main
  paths:
   include:
     - 'azure-pipelines.yml'
     - 'tasks/**/*'

jobs:
  - job: GetAkeylessSecrets
    displayName: 'Get Akeyless Secrets'
    pool:
      vmImage: 'windows-latest'
    steps:

    # Get credentials for Akeyless from Azure Service Principal
    - task: AzureCLI@2
      name: 'AzureCLI'
      inputs:
        azureSubscription: 'Azure MSA Account'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $JWT=$(az account get-access-token --query accessToken --output tsv)
          echo "##vso[task.setvariable variable=azure_jwt;isoutput=true;issecret=true]$JWT"
      displayName: 'Get JWT from Azure Service Principal'

    # Get static secrets
    - task: akeyless-secrets@1
      name: 'AkeylessStatic'
      inputs:
        accessid: 'p-sxfgaph9urt4om'
        azureJwt: '$(AzureCLI.azure_jwt)'
        staticSecrets: '{"/progress/TELERIK_NUGET_KEY":"nuget_key", "/docker/DOCKER_HUB_USERNAME":"docker_hub_un", "/apple/lance-apple-account-username":"apple_acct_un"}'
      displayName: 'Get Static Secrets'

    # Get dynamic secrets
    - task: akeyless-secrets@1
      name: 'AkeylessDynamic'
      inputs:
        accessid: 'p-sxfgaph9urt4om'
        azureJwt: '$(AzureCLI.azure_jwt)'
        dynamicSecrets: '{"/az-dvlup-sqlsrvsecret":"mySqlSecret", "/entra-id-live":"myEntraSecret"}'
        timeout: 30
      displayName: 'Get Dynamic Secrets'

    # Verify Outputs

    - powershell: |
        Write-Host "Output 1 (nuget_key): $(AkeylessStatic.nuget_key)"
        Write-Host "Output 2 (docker_hub_un): $(AkeylessStatic.docker_hub_un)"
        Write-Host "Output 3 (apple_acct_un): $(AkeylessStatic.apple_acct_un)"
      displayName: '[Static] Check static secret outputs'

    - powershell: |
        try {
          Write-Host "🧪 TEST 1 - Verify mySqlSecret's autogenerated outputs..."
          Write-Output "mySqlSecret_id: $(AkeylessDynamic.mySqlSecret_id)"
          Write-Output "mySqlSecret_password: $(AkeylessDynamic.mySqlSecret_password)"
          Write-Output "mySqlSecret_ttl_in_minutes: $(AkeylessDynamic.mySqlSecret_ttl_in_minutes)"
          Write-Output "mySqlSecret_user: $(AkeylessDynamic.mySqlSecret_user)"

          Write-Host "🏁---------------------------🏁"

          Write-Host "🧪 TEST 2 - myEntraSecret's autogenerated outputs..."
          Write-Output "id_secret_name: $(AkeylessDynamic.myEntraSecret_id_secret_name)"
          Write-Output "id_secret_key_id: $(AkeylessDynamic.myEntraSecret_id_secret_key_id)"
          Write-Output "msg: $(AkeylessDynamic.myEntraSecret_msg)"
          Write-Output "secret_appId: $(AkeylessDynamic.myEntraSecret_secret_appId)"
          Write-Output "secret_displayName: $(AkeylessDynamic.myEntraSecret_secret_displayName)"
          Write-Output "secret_endDateTime: $(AkeylessDynamic.myEntraSecret_secret_endDateTime)"
          Write-Output "secret_keyId: $(AkeylessDynamic.myEntraSecret_secret_keyId)"
          Write-Output "secret_secretText: $(AkeylessDynamic.myEntraSecret_secret_secretText)"
          Write-Output "secret_tenantId: $(AkeylessDynamic.myEntraSecret_secret_tenantId)"
          Write-Output "ttl_in_minutes: $(AkeylessDynamic.myEntraSecret_ttl_in_minutes)"
          Write-Host "🏁---------------------------🏁"

        } catch {
            Write-Output "Failed read the automatically generated outputs: $($_.Exception.Message)"
        }
      displayName: '[Dynamic] Autogen: Check individual outputs'

    - powershell: |
        Write-Host "🧪 TEST 1 - Parse mySqlSecret's plain output..."

        try {
          $sql = $env:SQL_SECRET_JSON | ConvertFrom-Json
          Write-Host "Available properties: $($sql.PSObject.Properties.Name -join ', ')"

          Write-Host "user: $($sql.user)"
          Write-Host "password: $($sql.password)"
          Write-Host "ttl_in_minute: $($sql.ttl_in_minute)"
          Write-Host "id: $($sql.id)"

          Write-Host "✅ Successfully parsed SQL dynamic secret's JSON."
        } catch {
          Write-Output "❌ Failed to parse SQL dynamic secret: $($_.Exception.Message)"
        }

        Write-Host "🧪 TEST 1 - Parse myEntraSecret's plain output..."

        try {
          $entra = $env:ENTRA_SECRET_JSON | ConvertFrom-Json
          Write-Host "Available properties: $($entra.PSObject.Properties.Name -join ', ')"

          Write-Host "keyId: $($entra.secret.keyId)"
          Write-Host "appId: $($entra.secret.appId)"
          Write-Host "tenantId: $($entra.secret.tenantId)"
          Write-Host "secretText: $($entra.secret.secretText)"
          Write-Host "endDateTime: $($entra.secret.endDateTime)"

          Write-Host "✅ Successfully parsed Entra ID dynamic secret's JSON."
        } catch {
          Write-Output "❌ Failed to parse Entra dynamic secret: $($_.Exception.Message)"
        }
      displayName: '[Dynamic] Simple Output: Parse the full response.'
      env:
        # IMPORTANT: See caution note https://github.com/LanceMcCarthy/akeyless-extension-azdo?tab=readme-ov-file#plain-output
        SQL_SECRET_JSON: $(AkeylessDynamic.mySqlSecret)
        ENTRA_SECRET_JSON: $(AkeylessDynamic.myEntraSecret)

