trigger:
  branches:
    include:
    - main
  paths:
   include:
     - 'azure-pipelines.yml'
     - 'tasks/**/*'

jobs:
  - job: Secrets_Check
    pool:
      vmImage: 'windows-latest'
    steps:
    # Get credentials from Azure DevOps Service Connection to authenticate to Akeyless
    - task: AzureCLI@2
      name: 'AzureCLI'
      displayName: 'Get JWT from Azure Service Principal'
      inputs:
        azureSubscription: 'Azure MSA Account'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $JWT=$(az account get-access-token --query accessToken --output tsv)
          echo "##vso[task.setvariable variable=azure_jwt;isoutput=true;issecret=true]$JWT"
    
    # Test static secrets retrieval
    - task: akeyless-secrets@1
      name: 'AkeylessStatic'
      displayName: 'Get Static Secrets'
      inputs:
        accessid: 'p-sxfgaph9urt4om'
        azureJwt: '$(AzureCLI.azure_jwt)'
        staticSecrets: '{"/progress/TELERIK_NUGET_KEY":"NUGET_KEY"}'

    - powershell: echo "Your output secret is $(AkeylessStatic.NUGET_KEY)"
      displayName: 'Check Static Secret output'

    # Test dynamic secrets retrieval
    - task: akeyless-secrets@1
      name: 'AkeylessDynamic'
      displayName: 'Get Dynamic Secret'
      inputs:
        accessid: 'p-sxfgaph9urt4om'
        azureJwt: '$(AzureCLI.azure_jwt)'
        dynamicSecrets: '{"/entra-id-dvlup":"entra_dynamic_secret"}'

    - powershell: |
        echo '$(AkeylessDynamic.entra_dynamic_secret)' | jq -r 'to_entries|map("AKEYLESS_ENTRA_ID_\(.key|ascii_upcase)=\(.value|tostring)")|.[]' >> $ENTRA
        echo $ENTRA
      displayName: 'Check Dynamic Secret output'