trigger:
  branches:
    include:
    - main
  paths:
   include:
     - 'azure-pipelines.yml'
     - 'tasks/**/*'

jobs:
  - job: Secrets_Check
    pool:
      vmImage: 'windows-latest'
    steps:
    # Get credentials from Azure DevOps Service Connection to authenticate to Akeyless
    - task: AzureCLI@2
      name: 'AzureCLI'
      displayName: 'Get JWT from Azure Service Principal'
      inputs:
        azureSubscription: 'Azure MSA Account'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $JWT=$(az account get-access-token --query accessToken --output tsv)
          echo "##vso[task.setvariable variable=azure_jwt;isoutput=true;issecret=true]$JWT"
    
    # Test static secrets retrieval
    - task: akeyless-secrets@1
      name: 'AkeylessStatic'
      displayName: 'Get Static Secrets'
      inputs:
        accessid: 'p-sxfgaph9urt4om'
        azureJwt: '$(AzureCLI.azure_jwt)'
        staticSecrets: '{"/progress/TELERIK_NUGET_KEY":"NUGET_KEY"}'

    - powershell: echo "Your output secret is $(AkeylessStatic.NUGET_KEY)"
      displayName: 'Check Static Secret output'

    # Test dynamic secrets retrieval
    - task: akeyless-secrets@1
      name: 'AkeylessSqlDynamic'
      displayName: 'Get SQL Dynamic Secret'
      inputs:
        accessid: 'p-sxfgaph9urt4om'
        azureJwt: '$(AzureCLI.azure_jwt)'
        dynamicSecrets: '{"/az-dvlup-sqlsrvsecret":"sql_dynamic_secret"}'

    - powershell: |
        $username=$(echo "$(AkeylessSqlDynamic.sql_dynamic_secret)" | jq -r '.user')
        $password=$(echo "$(AkeylessSqlDynamic.sql_dynamic_secret)" | jq -r '.password')
        $ttl=$(echo "$(AkeylessSqlDynamic.sql_dynamic_secret)" | jq -r '.ttl_in_minutes')
        $id=$(echo "$(AkeylessSqlDynamic.sql_dynamic_secret)" | jq -r '.id')
      displayName: 'Check SQL Dynamic Secret output'

    - task: akeyless-secrets@1
      name: 'AkeylessEntraDynamic'
      displayName: 'Get Entra Dynamic Secret'
      inputs:
        accessid: 'p-sxfgaph9urt4om'
        azureJwt: '$(AzureCLI.azure_jwt)'
        dynamicSecrets: '{"/entra-id-live":"entra_dynamic_secret"}'

    - powershell: |
        $keyId=$(echo "$(AkeylessEntraDynamic.entra_dynamic_secret)" | jq -r '.keyId')
        $displayName=$(echo "$(AkeylessEntraDynamic.entra_dynamic_secret)" | jq -r '.displayName')
        $appId=$(echo "$(AkeylessEntraDynamic.entra_dynamic_secret)" | jq -r '.appId')
        $tenantId=$(echo "$(AkeylessEntraDynamic.entra_dynamic_secret)" | jq -r '.tenantId')
        $secretText=$(echo "$(AkeylessEntraDynamic.entra_dynamic_secret)" | jq -r '.secretText')
        $ttl=$(echo "$(AkeylessEntraDynamic.entra_dynamic_secret)" | jq -r '.ttl_in_minutes')
        $endDateTime=$(echo "$(AkeylessEntraDynamic.entra_dynamic_secret)" | jq -r '.endDateTime')
      displayName: 'Check EntraID Dynamic Secret output'