name: 'Main'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'tasks/akeyless-secrets/**/*'
      - '.github/workflows/main.yml'

jobs:
  build-and-test:
    runs-on: windows-latest
    name: Run Tests
    env:
        NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: "Build and Run Tests"
      working-directory: '${{github.workspace}}\tasks\akeyless-secrets'
      run: npm run precommit
